# Jekyll Configs
permalink: /blog/:title.html
pygments: true
exclude: [config.ru, Gemfile, Gemfile.lock, LICENSE.txt, Procfile, Rakefile, README.md, vendor]
lsi: true

# Github style markdown
markdown: redcarpet
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "space_after_headers"]

# Site Information
title: Chris Garvis
production_url: "http://chrisgarvis.com"
description: "Code and other things"

analytics: inl3kuv44j

# Info about me
author:
  name: Christopher Garvis
  github: cgarvis
  linkedin: christophergarvis
  twitter: cgarvis
  email: cgarvis@gmail.com
